### ISSUE TITLE
Sinopé thermostat historique chauffage

### ISSUE THREAD

**Issue by fpitre75** [claudegel/sinope-gt130#2]
Bonjour Claude 
J'utilise depuis peu l'intégration Sinopé-GT130 . Je laisse la gestion des évènements de pointe d'Hydro-Québec a l'application Éco-Sinopé mais dans l'historique de Home Assistant il semble toujours avoir un de mes 6 thermostats qui n'arrête le chauffage a l'heure du début de l'évènement.  Je croyais du coté sinopé mais quand je regarde la consommation par heure sur leur application c'est plutôt du coté de home assistant ou l'intégration . Je vous envoie l'image de se matin pour le thermostat bureau. C'est aléatoire pour chaque évévenement matin ou soir 1 de 6 n'indique pas bien.  L'integration et home assistant sont a jour.

Le thermostat 'Bureau' la température 'current' descend, le 'target' est ok mais le 'heating'  continu d'afficher de 6:00 jusqu'a 6:5? comme si le chauffage était en fonction.

Je vous envoie un autre image historique d'un événement de pointe 19 janvier matin d'un autre thermostat.

Il m'arrive d'avoir dans mes log cette erreur mais semble être 1-3 par jour maximum

Logger: homeassistant.components.climate
Source: /usr/local/lib/python3.9/asyncio/events.py:80
Integration: Climate (documentation, issues)
First occurred: January 23, 2022, 5:41:47 PM (1 occurrences)
Last logged: January 23, 2022, 5:41:47 PM

Setup of climate platform neviweb130 is taking over 10 seconds.

Merci
 
![NeviwebGT130_2](https://user-images.githubusercontent.com/76669828/150798013-4e5c1824-bf00-4b8a-9991-e1527ffb6700.PNG)

![NeviwebGT130](https://user-images.githubusercontent.com/76669828/150795791-67df1f16-726d-4a28-8bfa-1ade3e2cecc1.PNG)

**Comment by claudegel** [comment]
Bonjour,

je suis en communication avec Sinopé pour ce genre de problème. Lorsque
le DR débute, Éco Sinopé envois une commande aux thermostats
participants pour qu'ils baissent le setpoint de 10oC (ou moins selon
ce que vous avez sélectionnez dans Éco Sinopé). Sur le thermostat on
voit que le setpoint a baissé de 10oC et qu'il ne chauffe pas. Par
contre sur Neviweb la consigne n'est pas ajustée et donc le setpoint
demeure à la température d'avant le DR et ça indique que le thermostat
chauffe.

Comme neviweb130 prend son information de Neviweb il n'y a pas moyen de
savoir que le setpoint est différent sur le thermostat par rapport à
Neviweb. IL est probable aussi que les informations de chauffage ne
sont pas mis à jour. Sinopé travail sur le problème mais avant, ils
doivent corriger la vitesse de démarrage du DR. Certaines personnes ont
rapporté qu'avec Éco Sinopé les thermostats coupent le chauffage
jusqu'à 10 minutes après le début du DR. Il y a le même problème à la
fin du DR alors que le chauffage revient jusqu'à 15 minutes après la
fin du DR.

J'imagine que transmettre toutes les consignes à des milliers de
thermostats ça ne se fait pas instantanément. Ils ont ajouté d'autre
attributs dernièrement pour le mode DR des thermostats. Je vais publier
une mise à jour aujourd'hui pour les ajouter pour les thermostats wifi.
j'ai déjà ajouté ces attributs pour les thermostats zigbee la semaine
passée.

Par contre si vous avez des automations qui gèrent la température
pendant la journée il faut les désactiver lors des pointes sinon elles
vont continuer à vouloir augmenter le chauffage le matin alors que Éco
Sinopé le coupe. Dans neviweb130 il y a maintenant un attribut
eco_status qui est à "on" quand le préchauffage débute et retourne à
"off" après le DR. Donc il faudrait ajouter dans vos automation qui
gèrent le setpoint de vos thermostats une condition que si eco_status
est "on" l'automation ne démarre pas le chauffage le matin.

Pour l'erreur:
Setup of climate platform neviweb130 is taking over 10 seconds.
Ça se produit au redémarrage de HA car avec toutes les applications à
redémarrer il arrive que certaines sont retardées et prennent plus de
10 secondes à démarrer. Ça n'affecte pas la suite des opérations. Le
démarrage des divers composants est aléatoire d'une fois à l'autre.

Ici j'ai plus de 40 appareils avec soit le GT125 en mode local et en
même temps en mode Neviweb et d'autres avec le GT130 ou avec ZHA et
j'ai, de temp en temps, cette erreur au redémarrage. Et comme je
redémarre souvent pour tester des modifications dans mes
custom_components avant de les publier mon RPI travaille fort.

Vérifiez le setpoint sur le thermostat pendant le prochain DR ainsi que
le chauffage et vous verrez que le thermostat ne chauffe pas mais que
Neviweb ne le sait pas.

Claude Gélinas

Le Mon, 24 Jan 2022 06:25:46 -0800
fpitre75 ***@***.***> a écrit:

> Bonjour Claude 
> J'utilise depuis peu l'intégration Sinopé-GT130 . Je laisse la
> gestion des évènements de pointe d'Hydro-Québec a l'application
> Éco-Sinopé mais dans l'historique de Home Assistant il semble
> toujours avoir un de mes 6 thermostats qui n'arrête le chauffage a
> l'heure du début de l'évènement.  Je croyais du coté sinopé mais
> quand je regarde la consommation par heure sur leur application c'est
> plutôt du coté de home assistant ou l'intégration . Je vous envoie
> l'image de se matin pour le thermostat bureau. C'est aléatoire pour
> chaque évévenement matin ou soir 1 de 6 n'indique pas bien.
> L'integration et home assistant sont a jour.
> 
> Le thermostat 'Bureau' la température 'current' descend, le 'target'
> est ok mais le 'heating'  continu d'afficher de 6:00 jusqu'a 6:5?
> comme si le chauffage était en fonction.
> 
> Je vous envoie un autre image historique d'un événement de pointe 19
> janvier matin d'un autre thermostat.
> 
> Il m'arrive d'avoir dans mes log cette erreur mais semble être 1-3
> par jour maximum
> 
> Logger: homeassistant.components.climate
> Source: /usr/local/lib/python3.9/asyncio/events.py:80
> Integration: Climate (documentation, issues)
> First occurred: January 23, 2022, 5:41:47 PM (1 occurrences)
> Last logged: January 23, 2022, 5:41:47 PM
> 
> Setup of climate platform neviweb130 is taking over 10 seconds.
> 
> Merci
>  
> ![NeviwebGT130_2](https://user-images.githubusercontent.com/76669828/150798013-4e5c1824-bf00-4b8a-9991-e1527ffb6700.PNG)
> 
> 
> ![NeviwebGT130](https://user-images.githubusercontent.com/76669828/150795791-67df1f16-726d-4a28-8bfa-1ade3e2cecc1.PNG)
> 
> 
> 



-- 
Claude Gélinas agr
Phyto Ressources Inc.

**Comment by fpitre75** [comment]
Merci beaucoup pour cette longue information pour le retour après le DR c'est arrivé quelques fois 15 minutes après mais je me doutais que le serveur était très occupé.

**Comment by claudegel** [comment]
Je continue à suivre l'évolution de Éco Sinopé et j'ajusterai
neviweb130 en conséquence

Claude Gelinas

Le Mon, 24 Jan 2022 08:56:47 -0800
fpitre75 ***@***.***> a écrit:

> Merci beaucoup pour cette longue information pour le retour après le
> DR c'est arrivé quelques fois 15 minutes après mais je me doutais que
> le serveur était très occupé. 
> 
>
