### ISSUE TITLE
Use zigbee TH1124ZB add to neviweb miss info/fonction in HA

### ISSUE THREAD

**Issue by fpitre75** [claudegel/sinope-gt130#3]
Bonjour Claude 
je vais écrire en français sera plus compréhensible. J'utilise vôtre intégration GT130 avec home assistant. 
Aujourd'hui j'ai ajouté 2 thermostat zigbee TH1124ZB (usagé) pour compléter mon installation.  J'ai éteint mon serveur car j'ai un dongle zigbee usb et je ne voulais pas que HA détecte ou interfère durant l'installation.
Installation compléter et paramètrer avec l'application Neviweb. J'ai ensuite redémarrer HA. 

Sur mon panneau j'ai ajouter les 2 nouveaux thermostat qui ont remonter de Neviweb avec le nom mais plusieurs info manquante et aucune température afficher et impossible d'ajuster. 

Je suis aller dans developer tool pour comparer une entité fonctionelle depuis l'intégration et la nouvelle entité j'ai changer les états manquant pour correspondre au donnée de neviweb et ensuite le thermostat et l'affichage fonctionnait. Voici les parametres changer . 

Entre le moment que j'ai installer les thermostats et verification dans HA un bon 30 minutes c'est écouler. 
 
min_temp: 0
max_temp: 0
current_temperature: null
temperature: null
wattage: 0
keypad: null
backlight: null
temperature_format: °C          VS       (thermostat fonctionnel  ) temperature_format: celsius 
setpoint_max: 0
setpoint_min: 0
unit_of_measurement: °C          VS     (thermostat fonctionnel )  unit_of_measurement: celsius

Mauvaise manipulation de ma part ? mais ceci dit maintenant semble très bien fonctionner

**Comment by claudegel** [comment]
Bonjour,
En fait l'intégration s'appelle neviweb130. Le GT130 etait au départ pour avoir une connection directe au GT130 comme mon autre integration sinope-gt125 qui se branche directement au GT125. Malheureusement Sinopé ne donne pas l'info sur l'API du GT130. 
Par contre il y a ZHA avec les gateway zigbee comme le Conbee II 
Quand vous branchez un nouveau thermostat dans Neviweb il faut le parametrer. Si vos thermostats ont été réinitialisés puisqu'usagés il est certain que les paramètres suivants sont à zéro ou Null:
Min_temp
Max_temp
Keypad
Backlight
temperature format
setpoint_max
setpoint_min
unit_of_measurement
Il faut aller dans le menu de configuration de chaque appareil sur Neviweb pour choisir des valeurs ou bien aller dans dev-tools de HA pour les configurer. neviweb130 ne fait que lire ces paramètres lors de la connection.
Pour wattage, si le thermostat n'a pas de demande il ne peut évaluer le wattage et il va le faire quand il va chauffer pendant quelques minutes.
Pour unit of measurement, si vous le définissez dans Neviweb ce sera celcius alors que si vous le faites via HA ce sera °C je pense.
Pour current_temperature: null et temperature: null il peut y avoir un délai au début si votre thermostat n'a pas transmit ses valeurs à Neviweb. En allant dès le branchement dans Neviweb pour configurer les autres paramètres ceci force une relecture des valeurs de température du thermostat et permet d'avoir ces valeurs immédiatement.
Neviweb130 ne lit pas les valeurs sur les thermostats mais les récupère de Neviweb alors ceci peut prendre quelques minutes.
En mode zigbee avec un Conbee II on lit les valeurs directement aux appareils. C'est instantané.
Je suis a développer une carte lovelace pour faire comme Neviweb et avoir une interface graphique pour configurer les papamètres de tous les appareils Sinopé. Encore pas mal de travail a faire mais ça s'en vient.

**Comment by fpitre75** [comment]
Merci je regarde se matin malgré que dans neviweb il sont programmés avec toys les details et sollicité cette nuit, rien encore. Hier avant de me coucher j'ai reparti le serveur les details entrées dans developement tool semble avoir été effacé ? Se matin j'avais  dans mes log 2 error pour les thermostat. J'ai pas regarder l'heure se matin j'ai redémarré le serveur et il sont revenu. Simplement au redémarrage ou  ..

Je vais remettre les détails fourni par neviweb dans l'entité avec developper tool et laisser rouler. Voici erreur si peut aider/utile.
This error originated from a custom integration.

Logger: custom_components.neviweb130.climate
Source: custom_components/neviweb130/climate.py:707
Integration: Sinope Neviweb130 (documentation)
First occurred: 8:59:36 AM (2 occurrences)
Last logged: 8:59:36 AM

Unknown error for neviweb130 climate Salle de bain: {'error': {'code': 'DVCATTRNSPTD', 'data': {'identifier': '500b914000010f7e'}}}... Report to maintainer.
Unknown error for neviweb130 climate Salle de Bain SS: {'error': {'code': 'DVCATTRNSPTD', 'data': {'identifier': '500b914000011105'}}}... Report to maintainer.

**Comment by claudegel** [comment]
Bonjour,

{'error': {'code': 'DVCATTRNSPTD', 'data': {'identifier': '500b914000011105'}}}
le DVCATTRNSPTD ca veut dire device attribute not supported. Je pense que c'est parce que vous n'avez pas fait toute la configuration dans Neviweb. Même si vous faite la configuration dans HA je ne suis pas certain si Neviweb va l'accepter si il n'y a pas une configuration de base de fait dans Neviweb pour ces appareils.

**Comment by fpitre75** [comment]
Bonjour Claude

 


Problème régler pour l’ajout de 2 thermostats seconde main Sinopé TH1124ZB 4000W avec votre intégration Neviweb130 via Neviweb portal. 


 J’avais aucune données autre que le nom de l’entité dans Home Assistant comme la photo jointe.


 



 

 

 

*	J’ai enlever l’intégration de HA et tous les traces ainsi que les thermostat en problème mon compte Neviweb et factory reset des 2 thermostats (aucun pairage zigbee) 

       -      Demander au vendeur de retirer (supprimer) les équipements de son comptes Neviweb

       -      Le lendemain matin réinstaller les 2 thermostats dans Neviweb avec un autre factory reset

       -      Attendu 3 heures. Données complète avec suivi de consommation des dernières heures

       -      J’ai réinstaller l’intégration Neviweb130 dans HA,  tous les thermostat ont été récupérer de mon compte Neviweb avec données,  sauf encore là aucun information autre que le nom d’entité pour les 2 thermostats seconde main ?

 

             Environ 3-4 heures après il ont apparue ?

 

La seul choses remarquer les 2 thermostats dans Neviweb les données étaient complète dans la configuration, mais version de matérielle = 0 ? et firmware différent des autres et maintenant firmware identique aux autres version avec matériel version 1

 

Par curiosité j’ai fait un factory reset d’un thermostat dernièrement installer (en problème dans HA) mais en redémarrant l’écran indique le dernier firmware 0.6.8 

 

Après avoir fait un restart serveur HA voici l’image du thermostat factory reset ,  (normal entity n’existe plus ) mais a coté le même thermostat (nouvelle entité) avec données récupérer lors du démarrage du serveur via portal Neviweb

 

 

 



 

Probablement tant que le thermostat n’a pas fait la mise a jour de son firmware, le thermostat était récupérer par l’intégration Neviweb130 via Neviweb portal mais aucune donnés étaient remontées dans HA, sinon était encore associer dans la base de donné avec l’ancien proprio mais pourtant les données était a jour et complète et plusieurs factory , après les avoir enlever de l’autre compte la veille.

 

Une note sur Github que l’ajout de thermostat zigbee et probable wifi, (seconde main ou différent firmware ) via Neviweb Portal peu prendre plusieurs heures  avant d’avoir les données pour ceux qui passe par le portail Neviweb serait bien,  car j’ai perdu énormément de temps ainsi et le vôtre.

 

 

Merci bonne journée

**Comment by claudegel** [comment]
Merci je vais regarder pour ajouter une note dans la documentation.
