### ISSUE TITLE
un ancien thermostat visible et 6 nouveaux non visible?

### ISSUE THREAD

**Issue by joelbibeau** [claudegel/sinope-gt130#4]
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.neviweb130.climate
Source: custom_components/neviweb130/climate.py:984
Integration: Sinope Neviweb130 (documentation)
First occurred: 14:00:22 (12 occurrences)
Last logged: 14:06:42

Unknown error for neviweb130 climate Chambre de Zakary: {'error': {'code': 'DVCATTRNSPTD', 'data': {'identifier': '588e81fffe95ed91-500b914000029081'}}}... Report to maintainer.
Unknown error for neviweb130 climate Garage: {'error': {'code': 'DVCATTRNSPTD', 'data': {'identifier': '588e81fffe95ed91-500b91400002802a'}}}... Report to maintainer.
Unknown error for neviweb130 climate Salle de bain: {'error': {'code': 'DVCATTRNSPTD', 'data': {'identifier': '588e81fffe95ed91-500b914000027f91'}}}... Report to maintainer.
Unknown error for neviweb130 climate Salle d’eau: {'error': {'code': 'DVCATTRNSPTD', 'data': {'identifier': '588e81fffe95ed91-500b914000028fb6'}}}... Report to maintainer.
Unknown error for neviweb130 climate Salon & cuisine: {'error': {'code': 'DVCATTRNSPTD', 'data': {'identifier': '588e81fffe95ed91-500b914000020acb'}}}... Report to maintainer.

**Comment by claudegel** [comment]
Bonjour vous n'avez pas écrit votre issue dans le bon répertoire mais c'est pas grave. Le bon répertoire est sinopé-130
premièrement DVCATTRNSPTD signifit device ettribute no supported. Il me faut le model de votre thermostat qui cause l'erreur

**Comment by claudegel** [comment]
envoyez-moi aussi le model de celui qui fonctionne.

**Comment by joelbibeau** [comment]
Woww
Merci à vous d’avoir pris le temps de me répondre



Envoyé de mon iPhone

________________________________
De : Claude Gelinas ***@***.***>
Envoyé : Sunday, December 18, 2022 2:55:20 PM
À : claudegel/sinope-gt130 ***@***.***>
Cc : Joël Bibeau ***@***.***>; Author ***@***.***>
Objet : Re: [claudegel/sinope-gt130] un ancien thermostat visible et 6 nouveaux non visible? (Issue #4)


Bonjour vous n'avez pas écrit votre issue dans le bon répertoire mais c'est pas grave. Le bon répertoire est sinopé-130
premièrement DVCATTRNSPTD signifit device ettribute no supported. Il me faut le model de votre thermostat qui cause l'erreur

**Comment by joelbibeau** [comment]
Celui-ci fonctionne

Je l’ai depuis deux ans environ
Il a été réinstallé à ma nouvelle maison avec la même passerelle GT130

Cependant les autres sont tous neuf

Merci

Envoyé de mon iPhone

________________________________
De : Claude Gelinas ***@***.***>
Envoyé : Sunday, December 18, 2022 2:59:15 PM
À : claudegel/sinope-gt130 ***@***.***>
Cc : Joël Bibeau ***@***.***>; Author ***@***.***>
Objet : Re: [claudegel/sinope-gt130] un ancien thermostat visible et 6 nouveaux non visible? (Issue #4)


envoyez-moi aussi le model de celui qui fonctionne.

**Comment by claudegel** [comment]
Pour plus de facilité je vais fermer cette issue et svp la réouvrir dans le bon répertoire
https://github.com/claudegel/sinope-130
ce sera plus facile pour modifier le code et le tester
Il me faut le model comme TH1123ZB de celui qui marche et de ceux qui ne marchent pas. Dans les nouveaux thermostats Sinopé modifit beaucoup les attributs et comme je n'ai pas tous les models je ne peux savoir ce qui a changé sauf si quelqu'un me le dit

**Comment by joelbibeau** [comment]
![image](https://user-images.githubusercontent.com/72266457/208317393-5657b094-5637-46b1-ae31-977e2abd6b5a.jpeg)

**Comment by joelbibeau** [comment]
![image](https://user-images.githubusercontent.com/72266457/208317404-62198d77-fffa-4d00-a5cd-71f7d22e1796.jpeg)

**Comment by joelbibeau** [comment]
![image](https://user-images.githubusercontent.com/72266457/208317434-930b085a-ff6e-45fd-8ab8-01085090927e.jpeg)

**Comment by claudegel** [comment]
Ce sont tous des TH1123ZB ? mais ceux qui ne marchent pas ont un firmware plus vieux, 0.6.5 alors que celui qui marche est un firmware 0.6.8.
Normalement ils devraient être mis a jour par Neviweb vers la version 0.6.8 et tout devrait rentrer dans l'ordre mais ceci peut prendre quelques jours.
Donc en attendant on va trouver quel attribut est pas supporté et mettre une exception dans le code.
Est-ce que ce sont tpous des TH1123ZB avec le même firmware?

**Comment by claudegel** [comment]
Dans vos log envoyez moi la ligne qui contient ceci
[custom_components.neviweb130] Received gateway data:...

**Comment by joelbibeau** [comment]
2x TH1123ZB V0.6.5 non fonctionnel
1x TH1123ZB V0.6.8 fonctionnel
4x TH1300ZB V1.0.9 non fonctionnel

**Comment by joelbibeau** [comment]
2022-12-18 14:00:18.832 DEBUG (SyncWorker_5) [custom_components.neviweb130] Received gateway data: [{'id': 354894, 'identifier': '588e81fffe95ed91-500b9140000213f2', 'name': 'Ch. maître', 'family': '737', 'signature': {'model': 737, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 9, 'middle': 0, 'major': 1}, 'hardRev': 0}, 'location$id': 41437, 'parentDevice$id': 354891, 'group$id': 152257, 'orderIdx': 0, 'sku': 'TH1300ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 354897, 'identifier': '588e81fffe95ed91-500b914000029081', 'name': 'Chambre de Zakary', 'family': '1123', 'signature': {'model': 1123, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 5, 'middle': 6, 'major': 0}, 'hardRev': 2}, 'location$id': 41437, 'parentDevice$id': 354891, 'group$id': 152260, 'orderIdx': 0, 'sku': 'TH1123ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 354892, 'identifier': '588e81fffe95ed91-500b914000028b00', 'name': 'Espace musique', 'family': '1123', 'signature': {'model': 1123, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 6, 'major': 0}, 'hardRev': 2}, 'location$id': 41437, 'parentDevice$id': 354891, 'group$id': 152261, 'orderIdx': 0, 'sku': 'TH1123ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 354896, 'identifier': '588e81fffe95ed91-500b91400002802a', 'name': 'Garage', 'family': '737', 'signature': {'model': 737, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 9, 'middle': 0, 'major': 1}, 'hardRev': 0}, 'location$id': 41437, 'parentDevice$id': 354891, 'group$id': 152258, 'orderIdx': 0, 'sku': 'TH1300ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 354891, 'identifier': '588e81fffe95ed91', 'name': 'GT130', 'family': 'GT130', 'signature': {'model': 130, 'modelCfg': 1, 'softBuildCfg': 0, 'softVersion': {'major': 2, 'middle': 3, 'minor': 0}, 'hardRev': 3}, 'location$id': 41437, 'parentDevice$id': None, 'group$id': 152262, 'orderIdx': 0, 'sku': 'GT130', 'vendor': 'Sinopé', 'url_en': 'https://www.sinopetech.com/produit/passerelle-zigbee/', 'url_fr': 'https://www.sinopetech.com/en/product/gateway-zigbee/'}, {'id': 354895, 'identifier': '588e81fffe95ed91-500b914000027f91', 'name': 'Salle de bain', 'family': '737', 'signature': {'model': 737, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 9, 'middle': 0, 'major': 1}, 'hardRev': 0}, 'location$id': 41437, 'parentDevice$id': 354891, 'group$id': 152259, 'orderIdx': 0, 'sku': 'TH1300ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 354898, 'identifier': '588e81fffe95ed91-500b914000028fb6', 'name': 'Salle d’eau', 'family': '1123', 'signature': {'model': 1123, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 5, 'middle': 6, 'major': 0}, 'hardRev': 2}, 'location$id': 41437, 'parentDevice$id': 354891, 'group$id': 152256, 'orderIdx': 0, 'sku': 'TH1123ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}, {'id': 354893, 'identifier': '588e81fffe95ed91-500b914000020acb', 'name': 'Salon & cuisine', 'family': '737', 'signature': {'model': 737, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 9, 'middle': 0, 'major': 1}, 'hardRev': 0}, 'location$id': 41437, 'parentDevice$id': 354891, 'group$id': 80208, 'orderIdx': 0, 'sku': 'TH1300ZB', 'vendor': 'Sinopé', 'url_en': None, 'url_fr': None}]

**Comment by claudegel** [comment]
Ok quel navigateur vous utilisez pour aller sur Neviweb?
On va ouvrir une console de débog pour aller chercher les attributs supportés et comparrer avec ceux demandés dans neviweb130

**Comment by joelbibeau** [comment]
Chrome

**Comment by claudegel** [comment]
OK dans chrome ouvrez votre Neviweb. Cliquer sur ctrl maj i pour ouvrir la console à droite
![console](https://user-images.githubusercontent.com/4268938/208320961-c6d7742f-00b0-4222-b800-46e104ec7596.jpg)
Voir les points encerclés en rouge 
Ouvrez votre thermostat qui ne marche pas. En premier un TH1123ZB pour trouver ses attribut (souligné à droite de la console) et refaites la même chose pour un TH1300ZB. Envoyez-moi les attributs

**Comment by joelbibeau** [comment]
{"roomTemperatureDisplay":27,"outputPercentDisplay":0,"roomSetpoint":13.5,"systemMode":"heat","errorCodeSet1":{"referenceSensor":"ok","compensationSensor":"ok","airSensor":"ok","wireSensor":"ok","currentOverload":"ok","thermalOverload":"ok","loadError":"ok","endOfLife":false},"drStatus":{"drActive":"off","optOut":"off","setpoint":"off","powerAbsolute":"off","powerRelative":"off"}}

**Comment by claudegel** [comment]
Ca c'est pour un TH1123ZB ?

**Comment by joelbibeau** [comment]
oui

**Comment by claudegel** [comment]
Ok envoyez-moi un TH1300ZB qui marche pas. Je vais commencer à verifier les attributs

**Comment by claudegel** [comment]
Svp quand vous sélectionnex un thermostat ouvrez aussi le panneau de configuration en cliquant sur l'icone de petire gear.
Il faut aussi valider les autres parametres.
Même chose pour le TH1300ZB

**Comment by joelbibeau** [comment]
j'arrive plus à retrouver la même ligne??

**Comment by joelbibeau** [comment]
il n'y à que roomSetPoint...

**Comment by claudegel** [comment]
Ca défile vers le bas si vous fermer le thermostat et vous l'ouvrez de nouveau la ligne va apparaitre au bas de la colonne de gauche dans la console. Puis ouvrez la configuration et la ligne devrait indéquer plus de parametres.

**Comment by claudegel** [comment]
C,est pas la ligne qui change mais une nouvelle qui apparait au bas de la colonne

**Comment by joelbibeau** [comment]
oui, mais il n'y à que des roomSetPoint

Anydesk?

**Comment by joelbibeau** [comment]
pour un TH1123ZB qui fonctionne pas
{"roomSetpoint":15.5,"roomTemperature":{"value":21.36},"outputPercentDisplay":0,"systemMode":"heat","errorCodeSet1":{"referenceSensor":"ok","compensationSensor":"ok","airSensor":"ok","wireSensor":"ok","currentOverload":"ok","thermalOverload":"ok","loadError":"ok","endOfLife":false}}


pour un TH1123ZB qui fonctionne
{"roomSetpoint":13.5,"roomTemperatureDisplay":26,"outputPercentDisplay":0,"systemMode":"heat","errorCodeSet1":{"referenceSensor":"ok","compensationSensor":"ok","airSensor":"ok","wireSensor":"ok","currentOverload":"ok","thermalOverload":"ok","loadError":"ok","endOfLife":false}}


pour un TH1300ZB qui fonctionne pas
{"roomSetpoint":15.5,"roomTemperature":{"value":12.39},"outputPercentDisplay":100,"gfciStatus":"ok","systemMode":"heat"}

**Comment by claudegel** [comment]
A date ca semble etre l'attribut roomTemperatureDisplay pour le TH1123ZB qui est pas supporté
Pour le TH1300ZB ca semble être la même chose
Un instant

**Comment by claudegel** [comment]
Pouvez-vous éditer le code de neviweb130 ?
il faudrait changer une ligne dans config/custom_components/neviweb130/climate.py

**Comment by joelbibeau** [comment]
avec file editor de HA, oui

**Comment by claudegel** [comment]
ok dans climate.py mettez un # devant la ligne 171 pour avoir
#    ATTR_ROOM_TEMP_DISPLAY,
redémarrez HA etdites moi ce que ca donne

**Comment by claudegel** [comment]
oups
`#    ATTR_ROOM_TEMP_DISPLAY,`

**Comment by claudegel** [comment]
On se reparle après le pouper. sinon bug avec mon boss :)

**Comment by joelbibeau** [comment]
redémarrage en cour

**Comment by joelbibeau** [comment]
plus aucun thermostat fonctionne 

bon souper, idem ici :)

**Comment by claudegel** [comment]
si ca marche il va falloir aussi commenter les lignes qui contiennent le parametre  ATTR_ROOM_TEMP_DISPLAY dans climate.py
vers les lignes 872, 920, 921
sinon ca va donner une autre erreur

**Comment by claudegel** [comment]
si plus aucun fonctionne valider dans les log de HA. il doit y avoir une erreur a propos d'un attribut  inconnu roomTemperatureDisplay. Il faut juste commenter les lignes ci-haut mentionnée
Si vous n'avez pas de log pour neviweb130 il faut ajouter dans configuration.yaml ceci
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```

**Comment by joelbibeau** [comment]
Ok
Je vérifie ça demain et vous reviens.

Merci pour votre temps
Très apprécié 👍🏻

Envoyé de mon iPhone

________________________________
De : Claude Gelinas ***@***.***>
Envoyé : Sunday, December 18, 2022 8:02:15 PM
À : claudegel/sinope-gt130 ***@***.***>
Cc : Joël Bibeau ***@***.***>; Author ***@***.***>
Objet : Re: [claudegel/sinope-gt130] un ancien thermostat visible et 6 nouveaux non visible? (Issue #4)


si plus aucun fonctionne valider dans les log de HA. il doit y avoir une erreur a propos d'un attribut inconnu roomTemperatureDisplay. Il faut juste commenter les lignes ci-ahut mentionnée
Si vous n'avez pas de log pour neviweb130 il faut ajouter dasn configuration.yaml ceci

logger:

  default: warning

  logs:

    homeassistant.custom_components: debug

    custom_components.neviweb130: debug

**Comment by joelbibeau** [comment]
Après avoir commenté la ligne 171 - 871 - 912 - 920, les 1123 fonctionne mais aucun 1300

**Comment by joelbibeau** [comment]
oups, 919 et non 912

**Comment by claudegel** [comment]
Donc on a trouvé ce qui boguait pour les 1123. Dans les logs est-ce qu'il y a quelques chose concernant les 1300.
Je vais fouiller de mon coté pour voir ce qui ne fonctionne pas pour tes 1300.
Ca pourrait être le parametre errorCodeSet1. Il semble manquant dans ton 1300

**Comment by claudegel** [comment]
Regarde dans climate.py vers la ligne 1008
if not self._is_wifi and not self._is_hc:
remplace par
if not self._is_wifi and not self._is_hc and not self._is_floor:
Ca va exclure le parametre errorCodeSet1 si jamais c'est lui qui manque

**Comment by joelbibeau** [comment]
aucune erreur mais malgré cette dernière modification, plus aucun thermostat n'est disponible

**Comment by claudegel** [comment]
Les 1123 ne fonctionnent plus ?
alors remettez la ligne 1008 comme avant et on va investiguer pour les 1300
Dans Neviweb ouvrez la console en faisant F12. puis ouvrez un 1300 et ouvrez aussi sa configuration. Envoyez mois les attributs pour que je vois si un attribut est absent.
Ensuite si possible envoyez moi les ligne de homeassistant.log qui contiennent les lignes suivantes:
1- [custom_components.neviweb130] Received gateway data:.....
2- [custom_components.neviweb130] Received signature data: {'signature': {'model': 737, '...
3- [custom_components.neviweb130.climate] Setting up neviweb130 climate **votre thermostat 1300**: {'id': 101013, 'identifier'...
4- [custom_components.neviweb130.climate] Updated attributes for neviweb130 climate

**Comment by joelbibeau** [comment]
Suite aux dernières mises à jour, tout fonctionne de mon coté.  mes 7 thermostats sont parfaitement fonctionnelle.  Merci pour tout
